project:
  type: website
  output-dir: docs


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  title: "Data Science Blog"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About Me"
        href: about.qmd
      - text: "Blog"
        href: blog/index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: Tutorials
        href: tutorials/index.qmd 
